# Generated by Django 3.1.3 on 2020-11-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('ingredients_image_url', models.URLField(max_length=2000)),
                ('recommended_image_url', models.URLField(max_length=2000)),
                ('great_for_image_url', models.URLField(max_length=2000)),
                ('ingredients', models.CharField(max_length=300)),
                ('recommended', models.CharField(max_length=300)),
                ('great_for', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditioner', to='product.product')),
                ('shampoo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shampoo', to='product.product')),
            ],
            options={
                'db_table': 'products_templates',
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'db_table': 'detail_images',
            },
        ),
        migrations.CreateModel(
            name='CategoryColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_url', models.URLField(max_length=2000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
            options={
                'db_table': 'categories_images',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.ManyToManyField(through='product.CategoryColor', to='product.Color'),
        ),
    ]
