# Generated by Django 3.1.3 on 2020-11-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='great_for',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='ingredients',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='recommended',
            field=models.CharField(max_length=500),
        ),
    ]
