# Generated by Django 3.1.2 on 2020-11-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='great_for_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ingredients_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recommended_image',
        ),
        migrations.RemoveField(
            model_name='detailimage',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product_image',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='great_for_image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='ingredients_image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='recommended_image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailimage',
            name='image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product_image_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
