# Generated by Django 3.1.3 on 2020-11-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201106_1322'),
        ('product', '0002_auto_20201109_0543'),
    ]

    operations = [
    ]
