# Generated by Django 3.1.3 on 2020-11-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragrance', models.CharField(max_length=30)),
                ('fragrance_image', models.URLField(max_length=1000)),
            ],
            options={
                'db_table': 'fragrances',
            },
        ),
        migrations.CreateModel(
            name='FragranceStrength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'fragrance_strengths',
            },
        ),
        migrations.CreateModel(
            name='HairGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=20)),
                ('silicone_free', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hair_goals',
            },
        ),
        migrations.CreateModel(
            name='HairStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_structure', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hair_structures',
            },
        ),
        migrations.CreateModel(
            name='HairType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hair_types',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_name', models.CharField(max_length=10)),
                ('fragrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fragrance')),
                ('hair_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.hairstructure')),
                ('hair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.hairtype')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='ScalpMoisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scalp_moisture', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'scalp_moistures',
            },
        ),
        migrations.CreateModel(
            name='QuizHairGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.hairgoal')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'db_table': 'quizzes_hair_goals',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='scalp_moisture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.scalpmoisture'),
        ),
        migrations.AddField(
            model_name='hairgoal',
            name='quiz',
            field=models.ManyToManyField(through='quiz.QuizHairGoal', to='quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='fragrance',
            name='fragrance_strength',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fragrancestrength'),
        ),
    ]
