# Generated by Django 3.1.2 on 2020-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairgoal',
            name='silicone_free',
        ),
        migrations.AddField(
            model_name='quiz',
            name='silicone_free',
            field=models.BooleanField(default=False),
        ),
    ]
