# Generated by Django 3.1.2 on 2020-11-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201107_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragrance',
            name='fragrance_strength',
        ),
        migrations.AddField(
            model_name='quiz',
            name='fragrance_strength',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.fragrancestrength'),
            preserve_default=False,
        ),
    ]
