# Generated by Django 3.1.2 on 2020-11-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201105_1337'),
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.orderitem'),
            preserve_default=False,
        ),
    ]
