# Generated by Django 3.1.2 on 2020-11-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201105_1337'),
        ('quiz', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='conditioner_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditioner_color', to='product.color'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.producttemplate'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shampoo_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shampoo_color', to='product.color'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
