# Generated by Django 3.1.3 on 2020-11-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_order_item'),
        ('cart', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.review'),
        ),
    ]
